import Head from "next/head";

import Header from "@/sections/Header";
import Banner from "@/sections/Banner";
import Social from "@/components/Social";

export default function Home() {

  return (
    <>
      <Head>
        <title>Glauko Pacheco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-[rgb(36,36,36)]">
        <Social />
        <Banner />
      </div>
    </>
  
  )
}
