import Head from "next/head";


import Header from "@/sections/Header";
import Banner from "@/sections/Banner";
import Nav from "@/sections/Nav";
import About from "@/sections/About";
import Services from "@/sections/Services";
import Work from "@/sections/Work";
import Contact from "@/sections/Contact";
import Social from "@/components/Social";

export default function Home() {

  return (
    <>

      <Head>
        <title>Glauko Pacheco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-site bg-no-repeat bg-cover overflow-hidden bg-[rgb(36,36,36)]">
        <Social />
        
        <Banner />
        <Nav />
        <About />
        <Services />
        <Work />
        <Contact />
        <div className="h-[320px]"></div>
      </div>
    </>
  
  )
}
